### ISSUE TITLE
Mininet branch 2.3.0d3 installs version 2.3.0d4

### ISSUE THREAD

**Issue by xbrakl** [mininet/mininet#822] opened 2018-08-29 13:18 UTC
I have just installed mininet with this script as root, on my VM with Ubuntu 16.04.5 LTS x64:

git clone git://github.com/mininet/mininet
cd mininet
git checkout -b 2.3.0d3
cd ..
mininet/util/install.sh -a
mn --test `pingall`

Then I checked OVS and Mininet versions and mininet has installed as 2.3.0d4 instead of 2.3.0d3

mn --version
``2.3.0d4``

then I checked just to be sure the branch of cloned repo and result was:

~/mininet# git branch
``*  2.3.0d3``
``    master``

**Comment by lantz** [comment] 2018-08-29 21:27
Thanks, should be fixed now.

**Comment by xbrakl** [comment] 2018-09-01 16:04
I have just got the same issue with the branch 2.2.2, again I setuped branch 2.2.2 and it was installed branch 2.3.0d4

**Comment by lantz** [comment] 2018-09-03 14:48
Thanks for the heads up. Probably a bad branch is shadowing a tag or something.

**Comment by lantz** [comment] 2018-09-03 15:05
Could you try the above commands and confirm that the versions are incorrect?

**Comment by lantz** [comment] 2018-09-04 02:31
It means that the branch tags are correct and that it will install the right version as intended.

**Comment by xbrakl** [comment] 2018-09-04 07:42
I am sorry, I dont know How could I help you. I am not so skilled in git. Anyways, I will keep this configuration for a week if you will need some more information.

If somebody needs to be sure with the version of installed mininet. Then he/she may download VM or install via command

sudo su -
apt install mininet

Each version of ubuntu installs now diferent version of the mininet according to the repos.
Specific list may be found here:
https://packages.ubuntu.com/bionic/mininet

Right now the best option is probably to install Ubuntu 18.04.1 LTS that has in the apt repositories mininet version 2.2.2.
Older versions of Ubuntu are dead already and have in repos mininet version 2.1 or lesser.

**Comment by lantz** [comment] 2018-09-04 13:03
make sure you are running the version you installed

**Comment by lantz** [comment] 2018-10-12 23:27
seems to be fixed.

**Closed by lantz** 2018-10-12 23:27 UTC
