### ISSUE TITLE
CGroups disappear from sysfs

### ISSUE THREAD

**Issue by maufl** [mininet/mininet#509] opened 2015-04-22 14:59 UTC
When ever I run mininet, all cgroup folders from /sys/fs/cgroup disappear. 
I have Arch Linux running and the version 2.2.0 of mininet.
I traced the problem to calling mnexec from startShell in the Host class. The mnexec call with which I can reproduce it is "mnexec -cdn env PS1=$ bash --norv -mis mininet:h1". I guess it is related to the mount() call on line 134 but I don't know. At this point I don't know how to debug it further.

**Comment by lantz** [comment] 2015-04-22 23:54
Can you please describe in detail the exact steps to reproduce the problem, the expected behavior, and the observed behavior?

**Comment by lantz** [comment] 2015-04-23 00:01
Looks OK on Ubuntu - mounted for root namespace, not mounted for host namespace:
```
$ sudo mn -v output
mininet> sh ls /sys/fs/cgroup
blkio  cpu  cpuacct  cpuset  devices  freezer  hugetlb	memory	net_cls  net_prio  perf_event  systemd
mininet> s1 ls /sys/fs/cgroup
blkio  cpuacct	devices  hugetlb  net_cls   perf_event
cpu    cpuset	freezer  memory   net_prio  systemd
mininet> h1 ls /sys/fs/cgroup
mininet> 
```
This looks like expected behavior to me.

**Comment by maufl** [comment] 2015-04-23 10:35
Maybe I was not clear enough. I do not have this problem in the virtual hosts but in my real host. I also tested it in the Ubuntu VM and can confirm that it works there. I now set up a new virtual machine with Arch to demonstrate my problem.

    .-(~)------------------------------------------------------(mctest@archtestbed)-
    `--> ls -al /sys/fs/cgroup
    total 0
    drwxr-xr-x 10 root root 240 Apr 23 12:27 .
    drwxr-xr-x  5 root root   0 Apr 23 12:29 ..
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 blkio
    lrwxrwxrwx  1 root root  11 Apr 23 12:27 cpu -> cpu,cpuacct
    lrwxrwxrwx  1 root root  11 Apr 23 12:27 cpuacct -> cpu,cpuacct
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 cpu,cpuacct
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 cpuset
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 devices
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 freezer
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 memory
    dr-xr-xr-x  2 root root   0 Apr 23 12:29 net_cls
    dr-xr-xr-x  4 root root   0 Apr 23 12:29 systemd
    .-(~)------------------------------------------------------(mctest@archtestbed)-
    `--> sudo mn
    *** Creating network
    *** Adding controller
    *** Adding hosts:
    h1 h2 
    *** Adding switches:
    s1 
    *** Adding links:
    (h1, s1) (h2, s1) 
    *** Configuring hosts
    h1 h2 
    *** Starting controller
    c0 
    *** Starting 1 switches
    s1 ...
    *** Starting CLI:
    mininet> exit
    *** Stopping 1 controllers
    c0 
    *** Stopping 2 links
    ..
    *** Stopping 1 switches
    s1 
    *** Stopping 2 hosts
    h1 h2 
    *** Done
    completed in 2.218 seconds
    .-(~)------------------------------------------------------(mctest@archtestbed)-
    `--> ls -al /sys/fs/cgroup
    total 0
    drwxr-xr-x 2 root root 0 Apr 23 12:30 .
    drwxr-xr-x 5 root root 0 Apr 23 12:29 ..
    .-(~)------------------------------------------------------(mctest@archtestbed)-
    `--> 
As you can see, after running mininet, all my cgroups are gone from /sys/fs/cgroup! I will continue to investigate.

**Comment by maufl** [comment] 2015-04-23 15:04
Soooo, it seems like when mnexec is executed, the unshare call is successfull. The bash process runs in a new mount namespace. However, when /sys is remounted, the new mount point is also visible in *all* processes and thus the cgroups are no longer visible (if I unmount the new mount point, the cgroups are visible again). It looks like the mount namespace is not working, could this be a kernel bug? O.o

**Comment by florianjacob** [comment] 2015-04-23 15:33
Same problem here, trying to give some more details on the setup.

I have a regular Arch Linux install, which currently ships the following versions:
```
mininet: 2.2.1
linux-kernel: 3.19.3
openvswitch: 2.3.1
systemd: 219 (might be relevant because of systemd-networkd?)
```

Steps to reproduce:

1. ```sudo pacman -S openvswitch```
2. ```yaourt -S mininet``` (or other way of installing mininet from AUR)
3. ```sudo systemctl start ovs-vswitchd```
4. ```ls -al /sys/fs/cgroup``` (to verify cgroups are there)
4. ```sudo mn```
6. ```ls -al /sys/fs/cgroup``` (to see all cgroups have vanished)

**Comment by maufl** [comment] 2015-04-23 17:06
Can you maybe past `/proc/mounts` after you ran mn?

**Comment by florianjacob** [comment] 2015-04-23 17:12
Here's my ```/proc/mounts```. 

```
$ cat /proc/mounts 
rootfs / rootfs rw 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=1985600k,nr_inodes=496400,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
/dev/sda / btrfs rw,relatime,compress=lzo,ssd,space_cache,user_subvol_rm_allowed 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
tmpfs /tmp tmpfs rw 0 0
tmpfs /run/user/995 tmpfs rw,nosuid,nodev,relatime,size=397764k,mode=700,uid=995,gid=995 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=397764k,mode=700,uid=1000,gid=1000 0 0
sysfs /sys sysfs rw,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
```

Just tried with ```linux-lts 3.14.39```, same result. I'll be right back from forcefully rebooting to get my cgroups again.

**Comment by maufl** [comment] 2015-04-23 17:16
As I expected, the last two entries are duplicates of the third and hide your original sysfs. This is why you can't see the cgroups anymore. Try `umount /sys` next time instead of rebooting, until the last two entries are gone.

**Comment by maufl** [comment] 2015-04-23 17:33
I can also reproduce it using the `unshare` programm. I guess that means it's not a mininet problem but a namespace problem in general. Steps to reproduce:
1. `sudo unshare -mn bash`
2. `mount -t sysfs sysfs /sys`
3. `exit`
4. `cat /proc/mounts`
Strangely, when using `unshare -m`, without network namespace isolation, it will not let me remount sysfs because it is already mounted or busy.

**Comment by florianjacob** [comment] 2015-04-23 19:14
I can reproduce the problem with unshare as well, and I can confirm that ```umount /sys``` fixes the problem for both, needed twice in the case of mininet. Didn't try ```unshare -m```.

You seem to know more about namespacing than me, where do you think we should report this bug next?

**Comment by maufl** [comment] 2015-04-23 19:38
I already reported it in the Arch Linux form. I don't know what else to do right now.

**Comment by florianjacob** [comment] 2015-04-23 20:17
Let's see whether someone knows what's going on there. For other people interested in this, the forum thread is at https://bbs.archlinux.org/viewtopic.php?id=196513 .

**Comment by lantz** [comment] 2015-04-23 21:06
Can you confirm that the problem occurs in the current Mininet VM image?

**Comment by maufl** [comment] 2015-04-24 09:26
No, this problem does not occur in the current Mininet VM image. It is not a Mininet Problem. Maybe we should close the ticket.

**Comment by lantz** [comment] 2015-04-24 20:04
Closing for now since it's not a Mininet bug and since it doesn't occur in Ubuntu/Debian/Fedora. Hopefully Arch can fix it upstream.

**Closed by lantz** 2015-04-24 20:04 UTC

**Comment by maufl** [comment] 2015-05-05 07:59
Ok, I found out what the problem is. I'm writing it here so that somebody might find it here in the future.

__This can become a problem for Mininet on other platforms too!!__

Since some time ago, systemd is mounting root as a shared mount point. This means, any mounts in root will be shared in both directions when mounting in a new mount namespace! I did not fully understand everything but you can read on shared mounts [here](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) and see the systemd commit [here](http://cgit.freedesktop.org/systemd/systemd/commit/?id=b3ac5f8cb98757416d8660023d6564a7c411f0a0). I found the solution [here](http://www.gossamer-threads.com/lists/linux/kernel/1722481). 
When changing into the new mount namespace, running `mount --make-rprivate /` will mark all mount points as private and subsequent mounts will not be shared. I don't know if this affects other operations of Mininet. I suggest you look into this as a lot of distributions nowadays use systemd.

**Comment by lantz** [comment] 2015-05-07 00:35
Ah, that's very irritating. Hopefully Ubuntu and Fedora won't do that!!

**Comment by ckannan** [comment] 2015-08-12 23:33
We ran into this today as we had packaged mininet for CloudRouter ( https://cloudrouter.org) which is based on Fedora / CentOS. https://cloudrouter.atlassian.net/browse/CR-126 . We should see a patch soon for this.

**Comment by thestinger** [comment] 2015-11-28 16:31
It's not correct to use mount namespaces without then setting MS_PRIVATE or MS_SLAVE if they are necessary. It makes sense for the default to be MS_SHARED since there's no way of obtaining that from *within* a mount namespace. It has to be set globally for it to work as expected. It's certainly not an Arch Linux bug.

**Comment by thestinger** [comment] 2015-11-28 16:32
Your software can't co-exist with anything requiring the MS_SHARED semantics if it makes the assumption that it isn't set, while that software does co-exist with everything else since MS_PRIVATE and MS_SLAVE can be (and are expected to be) set within mount namespaces without any loss of functionality.

**Comment by petosvk** [comment] 2016-01-14 23:36
Hi. Even his bug was closed, looks like it was not fixed. I am hitting this issue with recent fedora 23 (ovs 2.4.0 installed via dnf) and mininet 2.2.1 installed from source. What the fix is? Or what should i do locally to work around this issue?

**Comment by lantz** [comment] 2016-01-14 23:53
Can you confirm that the same problem occurs with current master?

**Comment by petosvk** [comment] 2016-01-15 00:55
Master is ok. Just 2.2.1 does this.
