### ISSUE TITLE
Connect Mininet and Snort

### ISSUE THREAD

**Issue by ngthtung** [mininet/mininet#828] opened 2018-09-17 06:31 UTC
Hello everyone,

I have a mininet, a controller ( floodlight ), a IDS ( Snort )
How can I connect mininet to Controller and IDS ?

I can connect mininet to Controller by :

> --controller=remote,ip=<controller's ip> port=<controller's port> 

but I still dont know how connect between mininet and IDS

Thank You.

**Comment by lantz** [comment] 2018-10-12 23:28
not a bug report - closing

**Closed by lantz** 2018-10-12 23:28 UTC
