### ISSUE TITLE
Miniedit bug Python3

### ISSUE THREAD

**Issue by lorenzomonta** [mininet/mininet#1046] opened 2021-03-03 10:46 UTC
Hello,

I would like to report the following bug in Miniedit:
When i run the command: "sudo python3 mininet/examples/miniedit.py", the result is the following exception:

mininet@mininet-vm:~$ sudo python3 mininet/examples/miniedit.py
topo=none
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "mininet/examples/miniedit.py", line 1452, in loadTopology
    self.appPrefs = dict(self.appPrefs.items() + loadedTopology['application'].items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

if I issue the following command instead: "sudo python2 mininet/examples/miniedit.py"
everything works fine!

**Comment by lantz** [comment] 2021-03-04 02:32
@lorenzomonta Can you confirm this error occurs in with `miniedit.py` in Mininet 2.3.0?

**Comment by lorenzomonta** [comment] 2021-03-04 07:55
Yes, occurs in Mininet 2.3.0

**Comment by lorenzomonta** [comment] 2021-03-04 15:38
```
mininet@mininet-vm:~$ sudo python3 `which mn` --version
2.3.0
mininet@mininet-vm:~$ python3 --version
Python 3.8.5
mininet@mininet-vm:~$ echo py sys.version | sudo python3 `which mn` -v output
mininet> 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]
mininet>
mininet@mininet-vm:~$ sudo HOME=~ python3 -m mininet.examples.miniedit
topo=none
mininet@mininet-vm:~$
```

this command: `sudo HOME=~ python3 -m mininet.examples.miniedit` open miniedit gui

**Comment by lantz** [comment] 2021-03-04 17:45
Great, looks like it is fixed in 2.3.0. Would you like to close this issue?

**Closed by lantz** 2021-03-04 17:45 UTC
Labels: discussion

**Comment by lorenzomonta** [comment] 2021-03-04 17:53
> Great, looks like it is fixed in 2.3.0. Would you like to close this issue?

Thank you! You are very kind to reply!

(Please can you read my last comment in #1048, after that I will not write any more, ecause it's driving me crazy)

**Comment by lorenzomonta** [comment] 2021-03-04 18:24
> Hmm, that's surprising. I am not seeing the code you show, nor that error, in Mininet 2.3.0.
> 
> Could you:
> 
>     1. Confirm that it happens in a Mininet 2.3.0 VM
> 
>     2. Try the following, both in a Mininet 2.3.0 VM and in your configuration:
>        ```
>        python3 `which mn` --version
>        python3 --version
>        echo py sys.version | sudo python3 `which mn` -v output
>        sudo HOME=~ python3 -m mininet.examples.miniedit
>        ```
> 
> 
> (Note that `HOME=~` is only necessary if you are running through an X11 tunnel.)
> 
> Thanks.

I said I would not write any more. But maybe this is a bug, if you run the command: `sudo HOME=~ python3 -m mininet.examples.miniedit` and try to import or export a topology or export the Python script, both files are empty. If you run the command: `sudo HOME=~ python2 -m mininet.examples.miniedit` this doesn't happen. Everything works correctly.
Just wanted to mention that.

**Comment by lantz** [comment] 2021-03-04 19:23
@lorenzomonta Thanks for testing MiniEdit under Python 3 - it's likely to have some bugs since there currently isn't automated testing for it.

Could you submit an issue along with detailed instructions on how to reproduce the issue?

**Comment by lorenzomonta** [comment] 2021-03-04 21:33
I have opened the issue, if I solve it I will open a pr
