### ISSUE TITLE
use of controller in mininet 

### ISSUE THREAD

**Issue by navnath1992** [mininet/mininet#540] opened 2015-07-25 06:10 UTC
1.I know its very cheap Q 
But I didn't clear my doubt that is 
If the two hosts are sending and receiving the packets then
 how the controller knows how much packet sent or received...
2.What is the use of controller .... 
Thnx

**Comment by wenhuizhang** [comment] 2015-07-26 18:55
There is a series number on TCP layer attached to the packet

**Comment by navnath1992** [comment] 2015-07-26 19:29
Sir but I didn't understand use of the controller

**Comment by lantz** [comment] 2015-07-26 21:36
Please do not abuse the github issues system for random questions that belong on the mailing list.
:(

Closing because this is not a bug.

**Closed by lantz** 2015-07-26 21:36 UTC

**Comment by wenhuizhang** [comment] 2015-07-27 00:34
controller is like a hypervisor layer of OS, also it is like a scheduler
