### ISSUE TITLE
RYU install get error

### ISSUE THREAD

**Issue by richardweib** [mininet/mininet#728] opened 2017-03-29 04:15 UTC
### Expected/Desired Behavior:

install ryu controller by `sudo ./install.sh -y`,and this script will install ryu

### Actual Behavior:

but when I run the command `sudo ./install.sh -y`,I get this error message:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '\\')

Storing debug log for failure in /home/shiyanlou/.pip/pip.log
```

so  I modify the install script:

```
#at 462 line
- sudo pip install --upgrade gevent pbr webob routes paramiko \\
+ sudo pip install --upgrade gevent pbr webob routes paramiko \
```
this is shell，not python.

and install ryu need install or update the requirement，if you do not install the requires you will get message like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ovs>=2.6.0
```

so I suggest add this command in script:

```
pip install -r ./tools/pip-requires
```

**Comment by lantz** [comment] 2017-05-24 21:55
Fixed with resolution of #744

**Closed by lantz** 2017-05-24 21:55 UTC

**Comment by arooj1994** [comment] 2022-08-22 22:52
While installing ryu wheever I go to ryu-manager I got an error called mutable error what does its mean? How I can remove it?

**Comment by ghazyayman** [comment] 2023-01-28 14:29
mutable error basically caused by a version conflict in the python library above 3.9.0 try downgrade your python version or change it with pyenv and install python 3.9.0
