### ISSUE TITLE
ping/iperf3 got unstable measurement results

### ISSUE THREAD

**Issue by ICYPOLE** [mininet/mininet#1138] opened 2022-06-08 03:35 UTC
### Expected/Desired Behavior:
Mininet should return stable ping RTT results, after setting the network conditions with Linux tc netem.

### Actual Behavior:
![image](https://user-images.githubusercontent.com/39186199/172525612-c407853a-4734-47e3-bbc7-0887d1d28f48.png)

### Detailed Steps to Reproduce the Behavior:
```bash
sudo mn # start the default topo h1---s1---h2
s1 tc qdisc add dev s1-eth2 root handle 1: netem delay 20ms loss 0.01% # this will emulate 20ms RTT
h1 ping h2 
```

### Additional Information:
I am running Mininet 2.3.0 on Virtual Box in my win10 laptop. I upgraded the Linux kernel to 4.15. 
Only a host-only adapter is set in VM:
![image](https://user-images.githubusercontent.com/39186199/172526208-76cb4958-4029-42b0-bdf6-7fb171959e22.png)

**Comment by Keshvadi** [comment] 2022-06-23 14:30
Did you test it without using Mininet? Sometimes tc netem does not work properly.

**Comment by ICYPOLE** [comment] 2022-06-23 14:50
> FYI, I have the same issue with VirtualBox running several CPUs If you don't need the multiple CPUs, note that there is no problem with only one CPU
> 
> Also, running mininet with a non-VirtualBox VM or without a VM works fine

I installed Mininet on virtual machine myself, instead of using VirtualBox image. Then it works out fine. Wonder why there is such a problem.

**Comment by ICYPOLE** [comment] 2022-06-23 14:51
> Did you test it without using Mininet? Sometimes tc netem does not work properly.

Seems like it has no relation with tc netem.

**Comment by janev94** [comment] 2022-11-10 13:40
I still see this even when I manually compile mininet from sources on a brand new VM. I am willing to provide code that will setup VM and compile mininet if that is useful.... 

Two questions:
1. Is there a way to have a VM with multiple CPUs but only assign a single to the mn controller (as this seems to fix the latency jitter?)
2. What version in particular did you install manually @ICYPOLE ? Is there a chance that this is mn version specific issue?

_Note:_ I need VM with multiple CPUs because otherwise my other processes on the VM are CPU starved, so, limiting the # of CPUs to 1 is not a valid option for me.

**Comment by lantz** [comment] 2022-11-10 22:31
This is almost certainly not a Mininet issue, and I was unable to reproduce it running on VMware.

It is most likely a configuration or resource issue with your setup.

As @Keshvadi suggested, you should try it on a loopback interface outside of Mininet.

**Comment by lantz** [comment] 2022-11-16 22:02
@ICYPOLE Since this doesn't appear to be a mininet issue, would you like to close it?

**Comment by lantz** [comment] 2022-11-22 01:38
Closing this for now. If you have a reproducible test case using the official VM image, we can reopen.

**Closed by lantz** 2022-11-22 01:38 UTC
Labels: can't reproduce
