### ISSUE TITLE
how to identify the ip address of mininet network?

### ISSUE THREAD

**Issue by skdff** [mininet/mininet#1098] opened 2021-12-06 16:40 UTC
![Screenshot (6)](https://user-images.githubusercontent.com/43513304/144885252-aa20b274-aa5b-48bc-9b14-29e121d3e729.png)
![Screenshot (7)](https://user-images.githubusercontent.com/43513304/144885373-f42cdead-7556-4bb4-bf44-e076e4e89cb8.png)
![Screenshot (8)](https://user-images.githubusercontent.com/43513304/144885437-5920a166-4e21-4d2d-a33d-04df7efd07e4.png)

Explanation:-

I have set up a preview of  ryu controller and mininet,but i am not able to identify the mininet ip address as well as not able to ping from other vm machine.But i am able to get the ip of mininet sub-host .Kindly help me .

**Comment by lantz** [comment] 2022-02-24 19:38
Please do not abuse github issues with requests for user assistance; you are welcome to use the mailing list however.
You may find it useful to read the MIninet documentation and also to look at examples/hwintf.py.
Closing because this is not a bug report.

**Comment by janev94** [comment] 2022-11-17 12:10
@lantz +1. I think this should be closed

**Closed** 2022-11-18 01:27 UTC
