### ISSUE TITLE
Error on installation in Ubuntu 15.10 amd64

### ISSUE THREAD

**Issue by ederollora** [mininet/mininet#601] opened 2016-03-04 13:45 UTC
The error is the following one:

> /oflops/traffic_generator.c:140: undefined reference to `time_diff'
> collect2: error: ld returned 1 exit status
> Makefile:574: recipe for target 'oflops' failed
> make[2]: **\* [oflops] Error 1
> make[2]: Leaving directory '/home/txapela/sdn/oflops'
> Makefile:639: recipe for target 'all-recursive' failed
> make[1]: **\* [all-recursive] Error 1
> make[1]: Leaving directory '/home/txapela/sdn/oflops'
> Makefile:431: recipe for target 'all' failed
> make: **\* [all] Error 2

Mininet seems to be installed but when I try a test command it gets stuck here:

>  sudo mn --test pingall
> **\* Creating network
> **\* Adding controller
> **\* Adding hosts:
> h1 h2
> **\* Adding switches:
> s1
> **\* Adding links:
> (h1, s1) (h2, s1)
> **\* Configuring hosts
> h1 h2
> **\* Starting controller
> c0
> **\* Starting 1 switches
> s1 ...
> **\* Waiting for switches to connect

I can't also install it again so any help would be nice. 

Thanks

**Comment by lantz** [comment] 2016-03-04 23:27
Can you please confirm that:

1) you are using the current master version of Mininet
2) you are installing with `mininet/util/install.sh -b`

And can you please include the entire build log from the above?
Thanks.

**Comment by ibbad** [comment] 2016-05-08 15:56
@surfoor  the problem is resolved if you stick to master branch and do not checkout on branch 2.2.1. However, it still does not resolve the issue.

sudo mn --test pingall
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Waiting for switches to connect

**Comment by ederollora** [comment] 2016-06-02 07:14
I had the same problem in both Ubuntu 15 and 16. The solution as said, was to checkout from master instead of 2.2.1 . Once done the installation seems to be ok. 

Running **sudo mn --test pingall** was succesful at least for me in Ubuntu 16.

**Comment by lantz** [comment] 2016-06-02 19:14
Closing - it's fixed in master as you have noted.

**Comment by haazy** [comment] 2017-03-06 15:04
Hello All, 

I am facing the same problem.

How do I use the master branch?

Thanks

**Comment by ederollora** [comment] 2017-03-06 15:14
Instead of checking out from 2.2.1, do it from master. You can see all the tags by typing:
`cd mininet` (inside mininet's root folder folder)
`user@host:~/mininet$ git tag`

To get the code from the master then just clone by NOT typing git checkout and just follow these commands. So:

`git clone git://github.com/mininet/mininet`
`mininet/util/install.sh [options]` (replace options with -a, -s ... or the option you want.)

**Comment by haazy** [comment] 2017-03-06 15:26
Thanks so much ederollora .


This works.

It's fine now

**Comment by surfoor** [comment] 2017-03-06 16:57
If it poosible for you try ubuntu 14.04 LTS which totally reliable for
dealing such controllers like mininet, openflow, pox and other sdn
controllers !
Hope it would help you !
On Mar 6, 2017 8:04 PM, "haazy" <notifications@github.com> wrote:

Hello All,

I am facing the same problem.

How do I use the master branch?

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mininet/mininet/issues/601#issuecomment-284421127>, or mute
the thread

**Comment by ederollora** [comment] 2017-03-06 17:04
I definitely back @surfoor 's words. 14,04 is perfect. There is enough support for mininet and also for additional controllers you may need. No need to go with 15 or 16 unless it is mandatory.

**Comment by haazy** [comment] 2017-03-06 18:14
16 is kind of mandatory for me.

Anyway I am getting this error. I am very new to mininet. This is my first time and I am just trying to get helpful resources online to set it up and practise with it so that I can become a guru one day.

![image](https://cloud.githubusercontent.com/assets/26226411/23622970/03801102-02a1-11e7-9380-d6d00cf3ebf4.png)

**Comment by ederollora** [comment] 2017-03-06 18:27
well @haazy  maybe when can help you switching to 14.04. Honestly most of the things are prepared for 14.04 and there is little support right now for 16. I would really consider on switching to 14.04, life just gets easier. 

In the meanwhile looks like there is a process running that interferes with the test you are trying to make. It looks its PID is 28802. Check OVS PID is that by running 

`ps aux | grep ovs`

I am guessing it is so try to run:

`sudo kill -9 28802`.  

the process should be kille. However you should know that in between mininet simulations you have to "clean" it. You do so by running:

`sudo mn -c`

Therefore when you run mininet tests and you stop them run the command above before you try again just to make sure there will be no conflicts. Let me know what is next.

**Comment by lantz** [comment] 2017-03-07 02:44
I'm opening up a new issue #720 for this, since it's something else.

Please create new issues rather than piggy-backing onto a close issue.

**Closed by lantz** 2017-03-07 02:44 UTC
